### ISSUE TITLE
Introspection modules don't 'recognise' being bound after restarts

### ISSUE THREAD

**Issue by zeroeightysix** [SquidDev-CC/ccjam-2016#104]
If a server restarts, introspection modules in manipulators will lose their ability to get player inventories when bound.

To reproduce:
1. Get a computer.
2: Place a manipulator next to it, on any side.
3. Get an introspection module and shift+click it to bind it to the player.
4. Place the introspection module in the manipulator.
5. Use the computer to wrap the manipulator and call any player-specific methods such as `getEnder` or `getInventory`.
6. The functions return the inventories as expected (a table).
7. Restart the server. In singleplayer this would just be logging out and back in.
8. Repeat step 5
9. Error - No such method for any of the player inventory functions.
10. Remove the introspection module from the manipulator and place it back in again ("refreshing it")
11. Repeat step 5, and the methods work as expected again.

A few screenshots to further explain:

Setup:
![The setup](https://shitty.download/VRaE.png)

Before a restart:
![Before a restart](https://shitty.download/GgvJ.png)

After a restart:
![After a restart](https://shitty.download/ED5R.png)

**Comment by SquidDev** [comment]
So the problem here is that the player doesn't exist when the peripheral is created, as they haven't joined the world yet. Consequently, the relevant methods aren't added as their predicates are not satisfied and so we get an error.

I'm not entirely sure of the best way of fixing this. It would be possible to add a magic "proxy" object, but it's likely to break other things which depend on there being an entity.
