### ISSUE TITLE
Expose forestry bee species list and breeding data

### ISSUE THREAD

**Issue by dmarcuse** [SquidDev-CC/ccjam-2016#111]
Methods on bee housing to get bee species and breeding data is a feature that OpenPeripheral had which was really nice for automation.

**Comment by dmarcuse** [comment]
I'd also be happy to write a PR for this (if I can get the other dependencies working)

**Comment by SquidDev** [comment]
Having a look at this, I wonder if these items would be better exposed on the item itself rather than the bee housing? This way people could get breeding information from normal inventories as well.

I'm always a little worried about exposing "internals" like this. It's sort of information I'd want to gate behind a Beealyser (a bit like I want to gate Thaumcraft stuff behind a Thaumometer), but I've no clue how to implement that.

**Comment by dmarcuse** [comment]
This data is already available through JEI, and doesn't really reveal any balance-breaking secrets, so I think it's ok from that perspective. Maybe it could be exposed by wrapping the [Analyzer](https://forestryforminecraft.info/breeding:analyzer) or [Portable Analyzer](https://forestryforminecraft.info/breeding:portableanalyzer)?
