### ISSUE TITLE
Overlay glasses object grouping

### ISSUE THREAD

**Issue by osmarks** [SquidDev-CC/ccjam-2016#141]
The ability to create "subcanvases" containing objects and clearable, etc separately would make it much easier to run multiple programs on the same set of overlay glasses.
Basically, the canvas would have a function to create a subcanvas, with the same API as the regular canvas.

**Comment by SquidDev** [comment]
It's on the roadmap, I just need to sketch out an implementation which is both performant and works with the existing network model.

**Comment by hugeblank** [comment]
Partial offtopic:

@osmarks In the event that you're referring to using shatter paired with another program, I plan on making the base canvas object available (`shatter.base?`), with a .clear() call that is modified so that it skips over all objects related to shatter. Just thought I'd mention that because it's likely something that will be available before squid gets to the implementation of this. _AND_ when this does get implemented, I'll make sure that shatter gets adapted to support it. :)

**Comment by hugeblank** [comment]
pfbbt... well I didn't expect it to be done _that_ quick.

**EDIT:** Squid are you even human?! 400+ additions in under 24 hours is god tier.

**Comment by SquidDev** [comment]
Someone suggested this months ago, and I only recently figured out a nice way of doing it. I'm not sure this counts!
