### ISSUE TITLE
Group2D doesn't inherit Scalable/Frame2D

### ISSUE THREAD

**Issue by hugeblank** [SquidDev-CC/ccjam-2016#159]
When you call `addGroup` it should also have sizing abilities (ex: `getSize`, and `setSize`?). It probably should behave more like the window API in CraftOS more than just a container to dump objects in. And anyways, you're able to set the position, so why not the two suggested in parentheses? :P

While developing Shatter I came across this and if I ran into it I think more people may in the future. Instead of having to feed the entire canvas into Shatter it would allow the ability to simply feed a group. Also this would allow for friendlier programming of splitscreen stuffs.

This may also apply to 3D objects but I have yet to tamper with that yet, so I don't know if it is something to consider there too.

**Comment by SquidDev** [comment]
I've discussed this elsewhere when the issue was first created, and forgot to comment here:

For now, I want groups to be as simple as possible: they're not meant to be a box around objects, with a size and clipping, but rather just a way to move several items together. This may change in the future, but I'm still at the stage where I'm working out the specifics of how overlay glasses are interacted with.
