### ISSUE TITLE
Redstone Integrator misleading redirection

### ISSUE THREAD

**Issue by hugeblank** [SquidDev-CC/ccjam-2016#208]
Was working on a little project with the redstone integrator when I came across this quirk that even though the integrator appears to redirect the signal into itself, when getting the input of that side the result is 0 (or false). If I add a block in place of the redstone where the integrator redirects the redstone, it works as intended giving me the output. A video is provided demonstrating the issue.

https://vimeo.com/331538687
(It's still processing at the time of reporting)

Using 1.12.2, Plethora 1.13.1, CC:T 1.80pr14

**Comment by SquidDev** [comment]
OK, so computers technically exhibit the same behaviour:

![Lit redstone wire attached to computer and lamp - both are off](https://user-images.githubusercontent.com/4346137/56494806-71273d80-64eb-11e9-8e69-be11e001c18e.png)

It's worth noting that pistons and lamps also behave this way. However, redstone does not connect to them, so that behaviour is understandable.

I'm not 100% sure if I want to change the computer's behaviour. It's definitely pretty questionable, but also don't want to break people's existing builds (though I doubt anyone has depended on this behaviour).

**Comment by hugeblank** [comment]
@SquidDev Since the wire has to indicate that the computer/integrator has outputting capabilities anyways, I think that the inputting behavior should follow suit. MC doesn't have any redstone components that do both inputting and outputting on a single side, so a perfect parallel can't be drawn, but repeaters and comparators _do_ have an input that redirects the wire into it, so it's not like input redirection doesn't exist at all.

**Comment by SquidDev** [comment]
CC:T behaviour has been changed in SquidDev-CC/CC-Tweaked#182, so I will update Plethora to reflect this.
