### ISSUE TITLE
Absolute coordinates through introspection module

### ISSUE THREAD

**Issue by idkw** [SquidDev-CC/ccjam-2016#228]
I'm not sure is this is a bug or a feature, but no matter what I do, any module that allow to get positional data (x,y,z) like the introspection module or the entity sensor give those coordinates relative to the owner of the neural interface.

This is indeed a good thing for some scripts but how can we compute the absolute coordinates from the relative coordinates ?

I looked everywhere and there seem to be no way to get the absolutes coordinates of the owner of the neural interface that would allow to convert other relative coordinates to absolute ones.

**With the introspection module getMetaOwner().x, .y and .z are always 0 so I'm assuming this is a bug. If not, how can we compute absolute coordinates** ? I have many scripts ideas that would require computing absolute coordinates but right now i'm kinda stuck.

Thanks

**Comment by SquidDev** [comment]
This is very much an intentional decision. One of the design choices I made in Plethora is that every module does one thing, and shouldn't (on its own) know anything extra.

A consequence of this is that everything is relative to the sensor or scanner - they're just meant to get information about nearby blocks or entities, not determine your position in the world.

Thankfully, this information is very easy to get - CC already provides a [GPS system](http://www.computercraft.info/wiki/Gps_(API)) to get your position in the world - from that it's easy to work out the absolute position of any nearby block/entity.

**Comment by idkw** [comment]
Ahah this is very RP, I like that, thank you !
