### ISSUE TITLE
peripheral access seems to result in dropped events

### ISSUE THREAD

**Issue by miiichael** [SquidDev-CC/ccjam-2016#239]
Hello,

Using plethora-1.12.2-1.2.2, cc-tweaked-1.12.2-1.84.0, forge-1.12.2-14.23.5.2847, and a number of other mods.

As development of my event-driven Extreme Reactors program progressed, I noticed an increasing tendency for events to be missed. Missing keypresses are usually harmless (if a little annoying after a while), but losing the regular timer event is more problematic.

Consider my [test program](https://gist.github.com/miiichael/4b0ac7767a9a2cc9875dfc88e4a94402). It assumes a computer connected to a vanilla furnace via a modem. If I comment out all the calls inside shenanigans(), the program behaves correctly. But otherwise, a large percentage of events go AWOL. Moving the shenanigans() call from the top of the main loop into the timer event handler somehow makes it somewhat less unreliable.

![image](https://user-images.githubusercontent.com/4179353/71422415-b627f300-26bc-11ea-8474-6897c668af96.png)

I'm wondering if something that Plethora is doing somehow interferes with the event queue. I did notice that calling .getDocs() didn't trigger this misbehaviour, whereas .getMetadata(), .list() and .size() did.

**Comment by SquidDev** [comment]
This is pretty much expected behaviour, and is a (sometimes unfortunate) side-effect of how ComputerCraft handles peripheral calls.

**Comment by SquidDev** [comment]
This is pretty much expected behaviour, and is a (sometimes unfortunate) side-effect of how ComputerCraft handles peripheral calls.

Basically, whenever CC needs to interact with the Minecraft world (such as listing items in a chest), we effectively stall the current task until the next time the server ticks, do whatever CC needs, and then resume the computer. Under the hood, this pretty much looks like:

```lua
function list()
  local task_id = queue_list_task()
  while true do
    local event, id, result = os.pullEvent("task_complete")
    if id == task_id then return result end
  end
end
```

As you can see, any other events are discarded. In itself, this isn't a problem - you'd get the same behaviour when using `rednet.receive` or `sleep`. It just ends up being a little confusing when trying to handle user input.

The correct thing to do here is to use the `parallel` API (see [this][cct] and [this][ccw]) to run your peripheral code and user-input code in tandem. This'd look something like this:

```lua
parallel.waitForAny(function()
  while true do
    -- Interact with peripherals here
    shenanigans(dev)
  end
end, function() 
  while true do
    local event = table.pack(os.pullEvent())
    -- Your input handling as before
  end
end)
```

[cct]: https://tweaked.cc/parallel.html
[ccw]: https://wiki.computercraft.cc/Parallel_API

**Comment by miiichael** [comment]
Thanks for your prompt and detailed response! Now excuse me while I go cry in the corner because I have to make invasive changes to the core of my program, instead of adding bells and whistles. :stuck_out_tongue: :sweat_smile:
