### ISSUE TITLE
3D Canvas objects can be obstructed by blocks

### ISSUE THREAD

**Issue by Vermenthruaxx** [SquidDev-CC/ccjam-2016#257]
Minecraft Version: 1.12.2 (forge 14.23.5.2768-stable)
CC:  Tweaked Version: 1.86.2
Plethora Version: 1.2.3

Going off the fact that the 2D canvas overlays the whole screen, not obstructed by blocks, 3D canvas blocks are obscured by blocks.

I.e. making an Ore Scanner program that uses 3D canvases will have the resulting ore boxes obscured by the cave blocks.

**Comment by SquidDev** [comment]
That's intentional - you can think of the 2d overlay as being overlayed on your eyes, while the 3d version is "present" in the world.

You can disable the depth testing [using these methods](https://squiddev-cc.github.io/plethora/methods.html#targeted-methods-org.squiddev.plethora.gameplay.modules.glasses.objects.object3d.DepthTestable) on the 3D cubes. See [this ore scanner version](https://github.com/SquidDev-CC/random-programs/blob/master/ore3d.lua) for instance.

**Comment by Vermenthruaxx** [comment]
Ohhhhhhh. Thanks! I was trying to find more information on stuff like this, and google searching for plethora 3d canvas stuff yielded totally irrelevant results. Even the plethora website didnt really give any useful examples for 3d canvases 😅 

So disabling depth testing will cause it to overlay, no matter what?

**Comment by SquidDev** [comment]
Yep. It may also interferer with other 3d objects though - 3d graphics are a pest to get right.

**Comment by Vermenthruaxx** [comment]
What kind of interference would it have?
Im not running many mods.
The only real "content mods" i have is Bibliocraft (furniture), IC2, and CC:Tweaked

**Comment by SquidDev** [comment]
It's nothing seriously glitchy, just semi-transparent objects may not always appear in the correct order, meaning _sometimes_ they don't show up. Most of the time you don't need to worry about it.

**Comment by Vermenthruaxx** [comment]
Ahhhhh, Thanks.
Ill try to see what I can do now that im armed with this info :)

Ive noticed that the 3D scanner has some issues placing things in the right spot, so Ill try to make my own program and see if i can directly solve this issue

Thanks!
