### ISSUE TITLE
Using inventory peripheral methods blocks char events

### ISSUE THREAD

**Issue by Sunlis** [SquidDev-CC/ccjam-2016#69]
Setup: [screenshot](https://i.imgur.com/Vq6efby.png)

Sample script:
```lua
chest = peripheral.wrap("top")

while true do
  chest.list()
  local ev,p1 = os.pullEvent()
  if p1 then
    print(ev .. " " .. p1)
  else
    print(ev)
  end
end
```

Expected output (pressing "a", "b", "c"):
```
key 30
char a
key_up 30
key 48
char b
key_up 48
key 46
char c
key_up 46
```

Actual output:
```
key 30
key_up 30
key 48
key_up 48
key 46
key_up 46
```

Not every inventory method blocks `char` events.

 Method | `char` events? 
----------------------|----------------
 drop | No 
 getDocs | Yes 
 getItem | No 
 getItemMeta | No 
 getMetadata | No 
 getTransferLocations | No 
 list | No 
 pullItems | No 
 pushItems | No 
 size | Yes 
 suck | No 

You **can** work around this, somewhat, by listening specifically for `char` events (ie. `os.pullEvent("char")`), but that prevents you from being able to listen for any other event types.

**Comment by SquidDev** [comment]
I'm really sorry for the delay in responding to this. I thought I'd typed something out, but evidently not. Anyway,

Due to how ComputerCraft and Plethora works internally, most peripheral methods (`.list()` included) will gobble all events until that function has finished executing. [There's a more thorough explanation here](http://www.computercraft.info/forums2/index.php?/topic/28796-), but this means `os.pullEvent` will only get the first event as a result of pressing a key, and `chest.list()` will delete the rest of them.

The best thing to do would be to use the `parallel.waitForAny` to pull `char` events in one function and list the chest in the other.
