### ISSUE TITLE
Function to get item metadata for all slots at once?

### ISSUE THREAD

**Issue by dmarcuse** [SquidDev-CC/ccjam-2016#76]
With [turtlegistics](https://github.com/apemanzilla/turtlegistics) I have to use `chest.list()` and then iterate the data, calling `chest.getItemMeta()` for every slot with items. Is there a reason there isn't a method to get all metadata at once?

**Comment by SquidDev** [comment]
There's a couple of reasons I'm rather reluctant to go here:

 - I realise this is rather trivial, but performance. Fetching metadata isn't super expensive, but if you start doing it across multiple inventories (especially large ones) it adds up. Obviously it's possible to fetch metadata for every slot in an inventory using the parallel API, but that is easier to rate limit using the cost system.

 - I generally try to avoid "god methods", namely methods which provide all the information you'd ever need. As you're forced to do things in a more roundabout way, it forces you to think about more efficient ways of doing things. I had a lot of fun optimising my item system to make as few method calls as possible.

A couple of tips to make things faster:
 - Cache aggressively. You can cache item metadata based on (id, damage, nbt) which means you don't need to fetch it for each tick. You can also cache items' location inside chests in order to optimise item transfer, etc... Heck, store the data to disk and verify it is correct on startup!

 - This isn't really relevant unless you're running on custom configs (like SwitchCraft1 was), but it's cheaper to use `.pullItem` on multiple peripherals than `.pushItem` on one peripheral. This allows you to speed up item transfer substantially.

**Comment by dmarcuse** [comment]
Alright, that makes sense. I'm already caching data in memory and only rescanning on command, it just takes several seconds to start and rescan.

With `pullItem` and `pushItem`, could you clarify what you mean? If I call `pullItem` on 3 chests to pull 10 items each from one stack in a fourth chest, that's faster than using `pushItem` on the fourth chest 3 times?

**Comment by SquidDev** [comment]
> If I call pullItem on 3 chests to pull 10 items each from one stack in a fourth chest, that's faster than using pushItem on the fourth chest 3 times?

Sometimes. I'm pretty sure SC2 is on default configs so it won't make a difference here, but if either of those methods have a "cost" then it is.
