### ISSUE TITLE
Overlay glasses Z fighting

### ISSUE THREAD

**Issue by Fokson** [SquidDev-CC/ccjam-2016#95]
When I draw something over something else the two drawables will flicker, unable to decide which one should be in front.  It seems to favor the **most recently drawn object** being behind, which it counter intuitive but workable.  But every few seconds the two will flicker back and forth for a moment before calming down.  Giving drawables a depth component would be nice, so they can be forced in front / behind another drawable.

Partially related, the color on random objects will flicker madly from time to time; I have no idea why this is.

**Comment by SquidDev** [comment]
What version are you on? This _should_ have been fixed in the latest version.

**Comment by SquidDev** [comment]
The flickering was fixed in 568db44b9ec46dde01f7365e9d5d09a2cc598804: it'll now consistently draw the most recent item on top.

I've added control over the z-axis to the todo list, though I'm not entirely sure how I want to go about it. There's several changes which need to be made to how terminal glasses elements are laid out, but I've not entirely decided on how it's all going to work

**Comment by Fokson** [comment]
I am using 1.1.10 for 1.10.2.  My apologies for forgetting to include that, it was very late =)
Seems that's the most recent version available for the version of Minecraft I'm using.

**Comment by SquidDev** [comment]
Thanks. For various reasons I'm not actively targeting 1.10.2 any more, but [you can download](https://www.dropbox.com/s/3mcltb2ur8atdqe/plethora-1.10.2-1.1.10-b0.jar?dl=1) a version with the given fix applied.

**Comment by Fokson** [comment]
Great, thank you so much! =)
