### ISSUE TITLE
.getMetaOwner() : .x .y .z don't give correct values anymore!

### ISSUE THREAD

**Issue by Wendelstein7** [SquidDev-CC/ccjam-2016#96]
It appears to me that in version plethora-1.12.2-1.1.10.jar the x y and z coordinates of the player within a block don't give the correct values!

Reproduce: stand at a random spot in a block.

Open your neural interface connector and enter a lua environment
modules = peripheral.find("neuralInterface")
meta = modules.getMetaOwner()
meta.x -- is always 0
meta.y -- weird numbers
meta.z -- always 0

Sorry for the low quality bug report

**Comment by SquidDev** [comment]
Thanks for the report! I'm assuming you mean 1.1.11, as 1.1.10 didn't change anything to do with the entity sensor.

d3e1cbd013ebc0ad23c970550486c94580670637 introduced a change to the entity scanner which made positions be computed relative to an object's position, rather than the block it was standing on. This is more useful when observing other entities, as the offset is more accurate. However, it's less ideal when you want to compute your position _within_ the block.

I'm not really sure what the best strategy here is: I'd like to keep the current behaviour, as I think it's more sensible, but I'm open to exposing entities' intra-block positions to the sensor.

**Comment by Wendelstein7** [comment]
Well personally for me (And my X-RAY scanner, I'm GoogleTech / HydroNitrogen) I used the meta x y z to get the offset within a block to get a smooth augmented overlay, because else the whole screen overlay would flicker/jump when one walks into a new block, as suddenly a whole meter to every point is added in 3D space. Currently I add the meta x y z offsetts so that I basically have the coordinates of all blocks in proximity as a float, rather than an integer. For me and especially my program it'd be really useful to have access to a players offset within a block.

And yes, I probably mean version *.11

And I'm not really used to writing bug reports, is this the correct way to communicate? More or less looks like a normal conversation :p

**Comment by SquidDev** [comment]
> And I'm not really used to writing bug reports, is this the correct way to communicate? More or less looks like a normal conversation :p

It's going to depend on the repo. As long as I have enough information to diagnose the issue I'm pretty chill. For larger repositories, they might require more information/a more structured report. For instance, see something [like this report](https://github.com/SpongePowered/SpongeForge/issues/2002).
